# TODO: Clean up the directory structure, it's a mess.

# Warning: Requires at least 3.5GB to build, maybe a bit more.

#http://myrocks.io/docs/getting-started/
FROM lamdencalrissian/seneca-myrocks-test:0.6
